# Generated by Django 4.1.3 on 2024-04-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_encuestarealizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areatrabajo',
            name='departamento',
        ),
    ]
