# Generated by Django 4.1.3 on 2024-05-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='documento',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='material',
            name='imagen',
        ),
    ]
