# Generated by Django 4.1.3 on 2024-05-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_documento_material_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='nombre',
            new_name='name',
        ),
    ]
