# Generated by Django 4.1.3 on 2024-05-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_material_created_at_material_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
