# Generated by Django 4.1.3 on 2024-06-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_material_created_at_alter_material_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosencuesta',
            name='pocentGeneral',
            field=models.FloatField(default=0, null=True),
        ),
    ]
