# Generated by Django 5.0.7 on 2024-08-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_resultadosencuesta_pocentgeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioinfo',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
